### PR TITLE
Improve robustness of the spec.md section extraction

### PR DESCRIPTION
**Pull request by dcermak**
cc @frostyx

### CODE REVIEW

**Comment by FrostyX** [comment]
@dcermak this is related to #148 or something else? Just to know what I should test.

**Comment by dcermak** [comment]
> @dcermak this is related to #148 or something else? Just to know what I should test.

Yes, #148 and #30

**Review by mcepl — APPROVED** [review]
LGTM, but I couldn’t test it because apparently there is some broken around my LSP client.

**Comment by FrostyX** [comment]
Possibly I am testing this wrong but I think #148 still happens. But this time with different functions and line numbers:

```
Traceback (most recent call last):
  File "/usr/local/bin/rpm_lsp_server", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/usr/local/lib/python3.12/site-packages/rpm_spec_language_server/main.py", line 46, in main
    server = create_rpm_lang_server()
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/rpm_spec_language_server/server.py", line 126, in create_rpm_lang_server
    rpm_spec_server = RpmSpecLanguageServer()
                      ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/rpm_spec_language_server/server.py", line 77, in __init__
    retrieve_spec_md() or ""
    ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/rpm_spec_language_server/extract_docs.py", line 198, in retrieve_spec_md
    with open(path) as spec_md_f:
         ^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/usr/share/doc/rpm/spec.md'
```

**Comment by dcermak** [comment]
> Possibly I am testing this wrong but I think https://github.com/dcermak/rpm-spec-language-server/issues/148 still happens. 

My bad! I've added a workaround for that and a regression test. It shouldn't happen now anymore.

**Comment by FrostyX** [comment]
Thank you for the update, I can confirm that it fixes #148 now.

**Comment by dcermak** [comment]
> Thank you for the update, I can confirm that it fixes https://github.com/dcermak/rpm-spec-language-server/issues/148 now.

Awesome, thank you!

**Pull request merged**
